import pycountry
from pydantic import BaseModel
from typing import Optional


class Author(BaseModel):
    name: str
    affiliation_text: Optional[str] = None
    department: Optional[str] = None
    institution: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    country: Optional[str] = None


class MeshTerm(BaseModel):
    term: str
    ui: str
    major_topic: bool


class Article(BaseModel):
    pmid: str
    title: str
    pub_year: int
    pub_month: Optional[str] = None
    journal: str
    authors: list[Author]
    mesh_terms: Optional[list[MeshTerm]] = []


# Static list of countries for matching affiliations
COUNTRIES = {c.name.lower(): c.alpha_3 for c in pycountry.countries}
# Add common variants
COUNTRIES.update(
    {
        "usa": "USA",
        "ar usa": "USA",
        "columbia mo usa": "USA",
        "u.s.a.": "USA",
        "u.s.": "USA",
        "us": "USA",
        "united states of america": "USA",
        "united states america": "USA",
        "united states states": "USA",
        "uk": "GBR",
        "u.k.": "GBR",
        "u.k": "GBR",
        "unitied kingdom": "GBR",
        "great britain": "GBR",
        "england": "GBR",
        "scotland": "GBR",
        "wales": "GBR",
        "czech republic": "CZE",
        "czechrepublic": "CZE",
        "czech republic-european union": "CZE",
        "korea": "KOR",
        "south korea": "KOR",
        "republic of korea": "KOR",
        "si republic of korea": "KOR",
        "korea (south)": "KOR",
        "republic of south korea": "KOR",
        "republic of, korea": "KOR",
        "north korea": "PRK",
        "taiwan": "TWN",
        "roc taiwan": "TWN",
        "slovak republic": "SVK",
        "palestine": "PSE",
        "vietnam": "VNM",
        "kosovo": "XKX",
        "trinidad": "TTO",
        "democratic republic of congo": "COD",
        "democratic republic of the congo": "COD",
        "republic of ireland": "IRL",
        "australian capital territory": "AUS",
        "upper austria": "AUS",
        "republic of türkiye": "TUR",
        "turkey": "TUR",
        "uae": "ARE",
        "republic of china": "CHN",
        "peoples republic of china": "CHN",
        "people's republic of china": "CHN",
        "jiangsu people's republic of china": "CHN",
        "hangzhou people's republic of china": "CHN",
        "people’s republic of china": "CHN",
        "people republic of china": "CHN",
        "people of republic of china": "CHN",
        "people's republic china": "CHN",
        "peoples' republic of china": "CHN",
        "jiangsu china": "CHN",
        "pr china": "CHN",
        "p. r. china": "CHN",
        "p.r.c.": "CHN",
        "prchina": "CHN",
        "shenzhen china": "CHN",
        "chongqing china": "CHN",
        "sar china": "CHN",
        "fujian china": "CHN",
        "countrychina": "CHN",
        "kingdom of saudi arabia": "SAU",
        "deutschland": "DEU",
        "iran": "IRN",
        "ir iran": "IRN",
        "swiss": "CHE",
        "brasil": "BRA",
        "belgique": "BEL",
        "méxico": "MEX",
        "russia": "RUS",
        "kemerovo russian federation": "RUS",
        "republic of singapore": "SGP",
        "austrian": "AUT",
        "the netherlands": "NLD",
        "kingdom of bahrain": "BHR",
        "argentine": "ARG",
        "republic of the gambia": "GMB",
        "all india": "IND",
        "venezuela": "VEN",
        "burkina": "BFA",
        "île-de-france": "FRA",
        "yugolav republic of macedonia": "MKD",
        "guyane": "GUF",
        "brunei": "BRN",
        "panamá": "PAN",
        "republic of panama": "PAN",
        "république du bénin": "BEN",
        "benin republic": "BEN",
        "zanzibar": "TZA",
        "espana": "ESP",
        "aotearoa-new zealand": "NZL",
        "guanajuato méxico": "MEX",
        "united kigndom": "GBR",
        "p.r.china": "CHN",
        "delft the netherlands": "NLD",
        "magyarország": "HUN",
        "r. macedonia": "MKD",
        "luxemburg": "LUX",
        "u.s.a .": "USA",
        "perú": "PER",
        "unites states of america": "USA",
        "united arab": "ARE",
        "república dominicana": "DOM",
        "fujianchina": "CHN",
        "kingdom of morocco": "MAR",
        "russian": "RUS",
        "p r china": "CHN",
        "república argentina": "ARG",
        "syria": "SYR",
        "czech": "CZE",
        "the gambia": "GMB",
        "united republic of tanzania": "TZA",
        "hunan china": "CHN",
        "norwa": "NOR",
        "new zeland": "NZL",
        "japanjapan": "JPN",
        "shandong people's republic of china": "CHN",
        "united.kingdom": "GBR",
        "saudia arabia": "SAU",
        "colorado usa": "USA",
        "qinghai china": "CHN",
        "birmingham al usa": "USA",
        "people' republic of china": "CHN",
        "eagle idaho usa": "USA",
        "unites states": "USA",
        "republic of malta": "MLT",
        "austria1": "AUT",
        "gb": "GBR",
        "uk2": "GBR",
        "houston texas usa": "USA",
        "aurora colorado usa": "USA",
        "moçambique": "MOZ",
        "hawaii": "USA",
        "wyoming": "USA",
        "guiyang china": "CHN",
        "republic of georgia": "GEO",
        "sénégal": "SEN",
        "tunisie": "TUN",
        "ivory coast": "CIV",
        "united staes": "USA",
        "iranian": "IRN",
        "dalian china": "CHN",
        "british": "GBR",
        "united state": "USA",
        "québec canada": "CAN",
        "allemagne": "DEU",
        "vilniuslithuania": "LTU",
        "cananda": "CAN",
        "pr people's republic of china": "CHN",
        "nitra slovakia": "SVK",
        "osterreich": "AUT",
        "tennessee": "USA",
        "irl": "IRL",
        "nippon": "JPN",
        "canadian": "CAN",
        "uk1": "GBR",
        "rus": "RUS",
        "españa": "ESP",
        "rus.": "RUS",
        "republic of n. macedonia": "MKD",
        "hawaii usa": "USA",
        "tanzania": "TZA",
        "estados unidos": "USA",
        "mėxico": "MEX",
        "telemark norway": "NOR",
        "malaysian": "MYS",
        "libyan": "LBY",
        "bolivia": "BOL",
        "polska": "POL",
        "republic of maldives": "MDV",
        "kansas usa": "USA",
        "algérie": "DZA",
        "kyrgyz republic": "KGZ",
        "urkey.": "TUR",
        "phillipines": "PHL",
        "laos": "LAO",
        "british colombia": "CAN",
        "the united states": "USA",
        "unted states of america": "USA",
        "florida usa": "USA",
        "people⿿s republic of china": "CHN",
        "cheonan republic of korea": "KOR",
        "commonwealth of australia": "AUS",
        "s. korea": "KOR",
        "zerbaijan.": "AZE",
        "henan china": "CHN",
        "austraila": "AUS",
        "soudan": "SDN",
        "united states of ameria": "USA",
        "irland": "IRL",
        "québec": "CAN",
        "mi usa": "USA",
        "nebraska usa": "USA",
        "jinan china": "CHN",
        "chinese": "CHN",
        "united kindom": "GBR",
        "republic of serbia": "SRB",
        "united emirates": "ARE",
        "french": "FRA",
        "new mexico": "USA",
        "suisse": "CHE",
        "indian": "IND",
        "galicia-spain": "ESP",
        "republic of moldova": "MDA",
        "grand duchy of luxembourg": "LUX",
        "oklahoma usa": "USA",
        "british columbia": "CAN",
        "bénin": "BEN",
        "paksistan": "PAK",
        "united kingdoms": "GBR",
        "turkiye": "TUR",
        "danish": "DNK",
        "united kingdon": "GBR",
        "hong kong sar china": "CHN",
        "trinidad  tobago": "TTO",
        "ürkiye.": "TUR",
        "irn": "IRN",
        "people's republic of bangladesh": "BGD",
        "callifornia": "USA",
        "hunan people's republic of china": "CHN",
        "loughborough uk": "GBR",
        "jinan people's republic of china": "CHN",
        "schweiz": "CHE",
        "killeen texas usa": "USA",
        "nanjing china": "CHN",
        "the united states of america": "USA",
        "netherland": "NLD",
        "jpn": "JPN",
        "urkiye.": "TUR",
        "fyr of macedonia": "MKD",
        "república de panamá": "PAN",
        "united kingom": "GBR",
        "republic of armenia": "ARM",
        "republic of macedonia": "MKD",
        "republic of north macedonia": "MKD",
        "denmar": "DNK",
        "united stated": "USA",
        "guizhou china": "CHN",
        "the philippines": "PHL",
        "laos people's democratic republic": "LAO",
        "italia": "ITA",
        "österreich": "AUT",
        "america": "USA",
        "i.r iran": "IRN",
        "german": "DEU",
        "nl": "NLD",
        "jimma ethiopia": "ETH",
        "wuxi china": "CHN",
        "u. s.": "USA",
        "sfax-tunisia": "TUN",
        "democratic people's republic of korea": "PRK",
        "sp/brazil": "BRA",
        "republic of koreas": "KOR",
        "palestinian territories": "PSE",
        "saudi- arabia": "SAU",
        "espoo": "FIN",
        "iowa usa": "USA",
        "republic of south africa": "ZAF",
        "henan people's republic of china": "CHN",
        "people' s republic of china": "CHN",
        "hainan china": "CHN",
        "the republic of korea": "KOR",
        "u.s.a": "USA",
        "nagoya japan": "JPN",
        "u. k.": "GBR",
        "sd usa": "USA",
        "elgium.": "BEL",
        "republic of austria": "AUT",
        "ningxia china": "CHN",
        "ussa": "USA",
        "west bengal": "IND",
        "algeriaalgeria": "DZA",
        "méxico méxico": "MEX",
        "florida": "USA",
        "shaanxi people's republic of china": "CHN",
        "baise china": "CHN",
        "urkey;": "TUR",
        "tx usa": "USA",
        "cameroun": "CMR",
        "islamic republic of iran": "IRN",
        "jiangxi people's republic of china": "CHN",
        "jiangxi china": "CHN",
        "danmark": "DNK",
        "new-zealand": "NZL",
        "nz": "NZL",
        "republic of azerbaijan": "AZE",
        "australian": "AUS",
        "rkiye.": "TUR",
        "united states of americ": "USA",
        "italie": "ITA",
        "sultanate of oman": "OMN",
        "shanxi china": "CHN",
        "austrailia": "AUS",
        "zhengzhou people's republic of china": "CHN",
        "republic of kazakhstan": "KAZ",
        "moldova": "MDA",
        "al usa": "USA",
        "federal republic of germany": "DEU",
        "peoples r china": "CHN",
        "yunnan china": "CHN",
        "macedonia": "MKD",
        "american": "USA",
        "michigan usa": "USA",
        "republic democratic of the congo": "COD",
        "nederlands": "NLD",
        "siovenia": "SVN",
        "guerrero méxico": "MEX",
        "northern ireland": "GBR",
        "brazzaville": "COG",
        "honolulu": "USA",
        "kobe": "JPN",
        "fujian": "CHN",
        "suzhouchina": "CHN",
        "yamanashi": "JPN",
        "mumbai": "IND",
        "malaga": "ESP",
        "toyama": "JPN",
        "az": "USA",
        "be": "BEL",
        "new york": "USA",
        "toyoake": "JPN",
        "ok usa": "USA",
        "poza rica": "MEX",
        "thai nguyen": "VNM",
        "tokyo": "JPN",
        "maryland": "USA",
        "guanajuato": "MEX",
        "tochigi": "JPN",
        "tunis": "TUN",
        "albany": "USA",
        "inner mongolia": "CHN",
        "balearic islands": "ESP",
        "guangxi": "CHN",
        "swansea uk": "GBR",
        "punjab": "IND",
        "guelph": "CAN",
        "kobe japan": "JPN",
        "rhode island": "USA",
        "jammu  kashmir": "IND",
        "south china": "CHN",
    }
)
